version: 2
updates:
  # Keep GitHub Actions up to date
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "03:00"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "github-actions"
    commit-message:
      prefix: "deps(actions)"

  # NuGet dependencies for all projects (src and tests)
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "daily"
      time: "03:15"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "nuget"
    commit-message:
      prefix: "deps(nuget)"
    allow:
      - dependency-type: "all"
    versioning-strategy: "increase"
    groups:
      minor-and-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

  # NPM (if/when package.json is introduced for frontend tooling)
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"
      time: "04:00"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "npm"
    commit-message:
      prefix: "deps(npm)"
    versioning-strategy: "increase"
